#!/bin/bash

ICON=$HOME/Documents/configs/i3/lock.png
TMPBG=/tmp/screen.png
TMPICON=/tmp/lock.png
scrot /tmp/screen.png
convert $TMPBG -scale 10% -scale 1000% $TMPBG
convert $ICON -scale 30% $TMPICON
convert $TMPBG $TMPICON -gravity center -composite -matte $TMPBG
i3lock -u -i $TMPBG
rm $TMPBG
